# Generated by Django 4.2 on 2025-10-13 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="primeiro nome"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="sobrenome"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="usuário"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="telefone"
                    ),
                ),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "restaurant"), (2, "customer")],
                        null=True,
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de adesão"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now=True, verbose_name="data de criação"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data de modificação"
                    ),
                ),
                ("is_admin", models.BooleanField(default=False, verbose_name="admin")),
                ("is_staff", models.BooleanField(default=False, verbose_name="staff")),
                ("is_active", models.BooleanField(default=False, verbose_name="ativo")),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="super usuário"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/profile_pictures",
                        verbose_name="imagem perfil",
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/cover_photos",
                        verbose_name="foto perfil",
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="endereço"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="complemento"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="país"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="estado"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="cidade"
                    ),
                ),
                (
                    "pin_code",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="CEP"
                    ),
                ),
                (
                    "latitude",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="latitude"
                    ),
                ),
                (
                    "longitude",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="longitude"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modificado em"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
