# Generated by Django 4.2 on 2025-10-02 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True, verbose_name="usuário"),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/profile_pictures",
                        verbose_name="imagem perfil",
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/cover_photos",
                        verbose_name="foto perfil",
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="endereço"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="complemento"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="país"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="estado"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="cidade"
                    ),
                ),
                (
                    "pin_code",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="CEP"
                    ),
                ),
                (
                    "latitude",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="latitude"
                    ),
                ),
                (
                    "logitude",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="logitude"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modificado em"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
